import type { Generated } from 'kysely';

interface ContactMessage {
  // Columns that are generated by the database should be marked
  // using the `Generated` type. This way they are automatically
  // made optional in inserts and updates.
  id: Generated<number>;

  name: string;
  
  message: string;

  created_at: Generated<Date>;

  seen: Generated<boolean>;

}
// Keys of this interface are table names.
export interface Database {
  contact: ContactMessage
}